<h1>Der IMDB-Datensatz</h1><br><br>
Dieser ist bereits in Keras enthalten und besteht aus einer Variablen, die zeigt, ob eine Review positiv ist und einer zweiten, welche die als Zahlen codierten Wörter der Review sind.

In [93]:
from keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = 10000)
print(train_data[0], '\n')
print(train_labels[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32] 

1


Der Datensatz ist bereits in einen Teil zum Testen und einen Teil zum Trainieren aufgeteilt. Mit <code>num_words = 10000</code> wird gesagt, dass die Daten nur die 10000 am häufigsten genutzten Wörter enthalten soll. Es wird also keine Zahl, die ein Wort codiert, 10000 übersteigen.

In [94]:
print('Anzahl Observationen im Trainingsset: ', len(train_labels))
print('Anzahl Observationen im Testset: ', len(test_labels))

Anzahl Observationen im Trainingsset:  25000
Anzahl Observationen im Testset:  25000


Hier ist außerdem ein Weg, wie du den Wortvektor zurück ins Englische übersetzen kannst:

In [95]:
index = imdb.get_word_index()
print(index['is'], '\n')
# 'is' ist das am sechst häufigsten genutzte Wort
# nun hast du einen assoziativen Array (Dictionary in Python) von Paaren (Wort, Zahl), das du umdrehen willst

indexReversed = dict([(number, word) for (word, number) in index.items()])
reviewNumbers = train_data[0]
print(review, '\n')
reviewWords = [indexReversed[num] for num in review]
print(' '.join(reviewWords))

6 

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32] 

the as you with out themselves powerful lets loves the

Da NNs keine Integers aufnehmen können, müssen die Vektoren von als Zahlen codierten Wörtern in One-Hot Codierung umgewandelt werden. Das heißt, jeder Vektor wird in einem Vektoren von 10000 Nullen umgewandelt, in dem eine 1 an den Stellen 6 und 14 sagen würde, dass diese Wörter ursprünglich im Vektor enthalten waren.

In [96]:
import numpy as np

def oneHottify(review):
    # len(review) Arrays, die jeweils 10000 Nullen besitzen
    results = np.zeros((1, 10000)).flatten()    
    for num in review:
        results[num] = 1        
    return results

review = train_data[0]
print(review, '\n')
print(oneHottify(review))

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32] 

[0. 1. 1. ... 0. 0. 0.]


In [97]:
i = 0
for vec in train_data:
    train_data[i] = oneHottify(vec)
    i += 1

i = 0
for vec in test_data:
    test_data[i] = oneHottify(vec)
    i += 1

print(train_data[10][:50])
print(test_data[10][:50])

[0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1.
 0. 0.]
[0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1.
 0. 0.]


Da wegen np.zeroes die Trainingsdaten bereits float32 NumPy-Arrays waren, müssen nun nur noch die Testdaten umgewandelt werden.

In [98]:
train_labels = np.asarray(train_labels).astype('float32')
test_labels = np.asarray(test_labels).astype('float32')

Nun wird das eigentliche Netzwerk gebaut:

In [100]:
from keras import models
from keras import layers

model = models.Sequential() # Bau der Schichten nacheinander
model.add(layers.Dense(16, activation = 'relu', input_shape = (10000, ))) # nimmt die 10000 one-hot arrays an
model.add(layers.Dense(16, activation = 'relu')) # dazwischen liegende Schicht von 16 Neuronen
model.add(layers.Dense(1, activation = 'sigmoid')) # Outputneuron für binäre Klassifikation

Das letzte Neuron wird einen Wert zwischen 0 und 1 ausgeben, kann also als Wahrscheinlichkeit für eine Klassifikation angesehen werden. Je näher an 0 oder 1, desto sicherer.

In [102]:
model.compile(
    optimizer = 'rmsprop',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

Um während des Trainings beurteilen zu können, wie gut das Modell funktioniert, muss dies an Daten getestet werden, die das Modell nicht zuvor gesehen hat. Im Gegensatz zum Testdatensatz wird dieses benutzt, um die Leistung während des Trainings zu beurteilen.

In [106]:
num_val_set = 10000

val_data = train_data[:num_val_set]
partial_train_data = train_data[num_val_set:]

val_labels = train_labels[:num_val_set]
partial_train_labels = train_labels[num_val_set:]

print(np.array(val_data))

[array([0., 1., 1., ..., 0., 0., 0.]) array([0., 1., 1., ..., 0., 0., 0.])
 array([0., 1., 1., ..., 0., 0., 0.]) ...
 array([0., 1., 1., ..., 0., 0., 0.]) array([0., 1., 1., ..., 0., 0., 0.])
 array([0., 1., 1., ..., 1., 0., 0.])]


Nun wird das Model gefittet und wird dabei in Dictionary zurückgeben, das den Verlauf des Trainings aufzeichnet.

In [104]:
history = model.fit(
    partial_train_data,
    partial_train_labels,
    epochs = 20,
    batch_size = 512,
    validation_data = (val_data, val_labels)
)

ValueError: Error when checking input: expected dense_1_input to have shape (10000,) but got array with shape (1,)