<h1>Das Beispiel-Netzwerk</h1><br>
Das zu lösende Probleme soll die Einordnung von 28px mal 28px großen Bildern von Zahlen in Schreibschrift in die Kategorien 0 bis 9 sein.

In [25]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

print(train_labels[0])
print(train_images[0])

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
5
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   

Nun wird ein Netzwerk gebaut, dem die Bilder train_images und die Zuordnung train_labels. Daraus entwickelt das Netzwerk Zuordnungen, die anhand des Vergleichs des errechneten Outputs von test_images[i] mit test_labels[i] verglichen werden.

In [17]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape=(28 * 28, )))
network.add(layers.Dense(10, activation = 'softmax'))

Wir bauen ein Netzwerk, das in der ersten Schicht 512 Einheiten besitzt und Daten der Größe <code>(28 * 28, )</code> erwartet. <code>Dense</code> heißt, dass jede Einheit dieser Schicht mit allen Einheiten der vorhergehenden Schicht verbunden ist. Die letzte Schicht besitzt eine <code>softmax</code> Aktivierungsfunktion, was bedeutet, dass sie 10 Wahrscheinlichkeiten für die 10 Kategorien zurückgeben wird.<br>
Nun müssen noch drei Dinge definiert werden, bevor das Netzwerk die Arbeite aufnehmen kann:
1. Die Loss-Function: wie das Netzwerk Erfolg beim Vergleich mit den Testdaten misst
2. Der Optimierer, also wie sich das Netzwerk optimiert, basierend auf der Loss-Function und den Daten
3. Die zu beobachtenden Metriken während des Trainings


In [18]:
network.compile(
    optimizer = 'rmsprop',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

Bevor das Netzwerk trainiert werden kann, müssen die Daten in Vektoren aus Nullen und Einsen umgewandelt werden. Unsere Trainingsbilder haben die Form <code>(60000, 28, 28)</code>, also 60000 Bilder mit 28 mal 28 Pixeln, wobei jeder Pixel durch eine Zahl zwischen 0 und 255 dargestellt wird, also wie schwarz/weiß dieser ist. Diese werden nun in <code>float32</code>-Werte <i>zwischen</i> 0 und 1 umgewandelt in der Form <code>(60000, 28 * 28)</code> (60000 Beobachtungen mit einem 1D-Array aus Werten zwischen 0 und 1).

In [19]:
train_images = train_images.reshape((60000, 28 * 28)) # neue Form mit flachen Arrays
train_images = train_images.astype('float32') / 255 # float32 auf 0...1 normiert

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

# labels umwandeln
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

# alles ist getan, das Netzwerk kann traniert werden
network.fit(
    train_images, train_labels,
    epochs = 5,
    batch_size = 128
)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('Accuracy:', test_acc)

Epoch 1/5
60000/60000 [==============================] - 6s 100us/step - loss: 0.2582 - acc: 0.9238
Epoch 2/5
60000/60000 [==============================] - 6s 93us/step - loss: 0.1038 - acc: 0.9690
Epoch 3/5
60000/60000 [==============================] - 6s 93us/step - loss: 0.0689 - acc: 0.9799
Epoch 4/5
60000/60000 [==============================] - 6s 93us/step - loss: 0.0496 - acc: 0.9851
Epoch 5/5
10000/10000 [==============================] - 1s 61us/step
Accuracy: 0.9796


<h1>Datenrepräsentationen</h1><br>
Tensoren sind die generelle Bezeichnung für Vektoren, Matrizen, Skalare, etc. Sie sind die in NN Netzwerk am meisten genutzte Datenrepräsentation.<br><br>
<b>Skalare - 0D</b><br>
Das sind Tensoren mit nur einer Zahl. In Numpy können float32 oder float64-Zahlen Skalare sein.<br><br>
<b>Vektoren - 1D</b><br>
Vektoren haben exakt eine Dimension, entlang der Zahlen angeordnet sind.<br><br>
<b>Matrizen - 2D</b><br>
Haben zwei Dimensionen, genannt Zeilen und Spalten.<br><br>
<b>3+D</b><br>
3D-Tensoren kann man z.B. als Anordnung in einem Würfel interpretieren.

In [20]:
import numpy as np
x = np.array(12)
print(x) # Skalar
print(x.ndim) # so kann man sich zeigen lassen, wie viele Dimensionen Tensor hat

print(np.array([12, 5, 2])) # Vektor
x = np.array([
    [1, 2, 4],
    [5, 2, 5],
    [6, 9, 2]
]).astype('float32')
print(x) # Matrix

12
0
[12  5  2]
[[1. 2. 4.]
 [5. 2. 5.]
 [6. 9. 2.]]


<h1>Manipulation von NumPy-Datentypen</h1><br>
Tensoren haben folgende wichtige Eigenschaften:

In [23]:
print(x.ndim) # Zahl der Achsen
print(x.shape) # wie viele Einheiten entlang jeder Achse: hier 3 Zeilen, 3 Spalten
print(x.dtype) # der NumPy-Datentyp

print(train_images.ndim)
print(train_images.shape)
print(train_images.dtype)


2
(3, 3)
float32
2
(60000, 784)
float32


<b>Auswählen von Daten aus einem Tensor</b><br>

In [26]:
mySlice = train_images[10:100] # Auswahl Beobachtungen 1 bis 99
print(mySlice.shape)
# ist das gleiche wie
mySlice = train_images[10:100, 0:28, 0:28]
print(mySlice.shape)

# Auswahl der unteren rechten Ecke ALLER Bilder:
mySlice = train_images[:, 14:, 14:] # alle Bilder, Px 14 und darüber, px 14 und darüber


(90, 28, 28)
(90, 28, 28)
